Make compression algorithm configurable for parquet format
streamnative/pulsar-io-cloud-storage pull request #469
Opened 2022-10-17 09:07 UTC by nicoloboschi

### Motivation
In the parquet format the compression is always `gzip`. The compressor mechanism passes through the hadoop library that has a memory leak for the gzip codec, see https://issues.apache.org/jira/browse/HADOOP-12007
There's no fix available yet. The only way to avoid the leak it would be to use another algorithm. 

### Modifications

* Added new config option `parquetCodec` (similar to ´AvroCodec´) that accepts a String. The string must be a available compression algorithm. The default value is still `gzip` for compatibiliy.
* Added docs

### Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (docs)

2022-10-17 14:02 UTC, alpreu requested changes
Good catch, thanks a lot for this! 

Could you please add the README changes also to `docs/cloud-storage-sink` ? It would also be good to add a note to both, stating that the default gzip compression leaks memory with a link to the JIRA

2022-10-17 20:28 UTC, nicoloboschi commented
After more testing I realized that we don't really hit the mentioned bug because usually there's no native hadoop library in the Pulsar container. In that case a simple GZIPOutputStream is used. 

I think we can still merge this pull but there's no need to update the docs

2022-10-18 08:44 UTC, alpreu commented
Oh well :) Could you still add the new configs also to /docs/cloud-storage-sink? Thanks

2022-10-18 10:16 UTC, nicoloboschi commented
> Oh well :) Could you still add the new configs also to /docs/cloud-storage-sink? Thanks

done!

2022-10-18 11:19 UTC, alpreu approved these changes

2022-10-18 11:20 UTC, merged